channels:
- conda-forge
dependencies:
- python=3.11.10
- pip<=24.2
- pip:
  - mlflow==2.18.0
  - cloudpickle==3.1.0
  - numpy==1.26.4
  - psutil==5.9.8
  - scikit-learn==1.5.0
  - scipy==1.13.0
name: mlflow-env
